### ISSUE TITLE
Provide for font selection in printbadge handler.

### ISSUE THREAD

**Issue by shevett** [shevett/congo#349]
You can specify the font size within the XML, but not the font itself.  Add a selector in the SAX parser that allows for a font name as well as the existing size.

**Comment by dkapell** [comment]
This is tested and checked in.  There is a new attribute "font" which can be set to "helvetica", "times" or "courier" or a path to a font file on disk.  If the path is invalid, it will default back to helvetica.  This is documented on the EditEvent page along with #359 and #360
